server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/test?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-circular-references: true

mybatis-plus:
  #配置mybatis-plus逻辑删除
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  #配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 阿里云OSS配置
aliyun:
  oss:
    end-point: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t6Th7kmiG4E6WJLgMC3
    access-key-secret: eDPHoAEq7nJXAtEOELYFPGaM19K2CP
    bucket-name: qqq-ceshi
