server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/test?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-circular-references: true

mybatis-plus:
  #配置mybatis-plus逻辑删除
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  #配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl