server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/test?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-circular-references: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: qqq
    password: qianqiang0216
    #虚拟主机
    virtual-host: testHost
    #确认消息已发送到交换机(Exchange)
    #publisher-confirms:true
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true

mybatis-plus:
  #配置mybatis-plus逻辑删除
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  #配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 阿里云OSS配置
aliyun:
  oss:
    end-point: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t6Th7kmiG4E6WJLgMC3
    access-key-secret: eDPHoAEq7nJXAtEOELYFPGaM19K2CP
    bucket-name: qqq-ceshi
  #阿里视频直播
  live:
    #推流
    pushDomin: livepush.zjtuojing.com
    pushIndentKey: 0qFNOkPoKyymwAcD
    #播流
    pullDomin: livepull.zjtuojing.com
    pullIdentKey: cY0Pm61uQ2ooURCS
    #appName自定义
    appName: test
    #鉴权url过期时间 有效时间（秒）
    identUrlVaildTime: 1800
